### ISSUE TITLE
Add culori to benchmark

### ISSUE THREAD

**Issue by ai** [texel-org/color#2]
Hi. I am very interested in new color library for [oklch.com](https://oklch.com/).

We are using [culori](https://culorijs.org) and if benchmark will show that your tool is faster I will think about switching.

Can you add it to benchmark?

**Comment by mattdesl** [comment]
I've added a culori benchmark inside `test` folder, which tests converting OKLCH to P3 and then gamut mapping to P3. I'm not familiar with their API so if there is a more optimal method of doing that, let me know.

```sh
Testing with input type: Random Samling in P3 Gamut
Conversion OKLCH to P3 --
Culori: 49.56 ms
Ours: 17.03 ms
Speedup: 2.9x faster

Gamut Mapping OKLCH to P3 Gamut --
Culori: 1568.37 ms
Ours: 23.90 ms
Speedup: 65.6x faster

Testing with input type: Random Samling in OKLab L Planes
Conversion OKLCH to P3 --
Culori: 42.38 ms
Ours: 12.84 ms
Speedup: 3.3x faster

Gamut Mapping OKLCH to P3 Gamut --
Culori: 1555.23 ms
Ours: 22.89 ms
Speedup: 68.0x faster
```

I've also benchmarked the bundle size: it is smaller than Colorjs, coming in at ~43 kb (compare to ~3.5 kb for @texel/color).

It should be noted that `@texel/color` is effectively a bit lower-level than culori; it doesn't aim to have complete parsing/serialization that matches CSS spec, which I've enjoyed as a feature of [oklch.com](https://oklch.com/) input fields, so I doubt you'd be able to move off it completely. I would probably only consider the swtich if you feel your app is bottlenecked; or perhaps only use `@texel/color` to optimize the hot code paths, but note it will introduce slight differences in results (the matrices in culori do not seem to match exactly, I haven't dug into what they are using).

**Comment by ai** [comment]
Amazing, thanks. I added task to try `@texel/color` at least for chart painting.

**Comment by danburzo** [comment]
Thanks @mattdesl for including Culori in the benchmark (author here), and congrats on the project, the performance looks amazing on what is probably the most computationally-intensive color operation! We are using binary search for gamut mapping, which throws a wrench into the Big O, so I’m not surprised by the difference :-) I’ve added `@texel/color` to the [list of resources](https://culorijs.org/resources/).
