### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by ai** [texel-org/color#3]
TypeScript is very popular. For instance, we are using TS in [oklch.com](https://oklch.com/).

Adding types will create a good reason to switch compare to other color libraries.

**Comment by mattdesl** [comment]
I plan to add types in comments, similar to [png-tools](https://github.com/mattdesl/png-tools), which may be helpful for TS users consuming the library.

**Comment by bengry** [comment]
> I plan to add types in comments, similar to [png-tools](https://github.com/mattdesl/png-tools), which may be helpful for TS users consuming the library.

Would you be open to accepting PRs adding types in a `.d.ts` file in this repo? Rather than having a separate `@types/texel__color` package on https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by skorphil** [comment]
> > I plan to add types in comments, similar to [png-tools](https://github.com/mattdesl/png-tools), which may be helpful for TS users consuming the library.
> 
> Would you be open to accepting PRs adding types in a `.d.ts` file in this repo? Rather than having a separate `@types/texel__color` package on https://github.com/DefinitelyTyped/DefinitelyTyped.

Have you found types for texel there? Oo I cant see them there

**Comment by bengry** [comment]
> > > I plan to add types in comments, similar to [png-tools](https://github.com/mattdesl/png-tools), which may be helpful for TS users consuming the library.
> > 
> > 
> > Would you be open to accepting PRs adding types in a `.d.ts` file in this repo? Rather than having a separate `@types/texel__color` package on [DefinitelyTyped/DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).
> 
> Have you found types for texel there? Oo I cant see them there

I have [written some partial types](https://gist.github.com/bengry/caa2d602db5c011d12d4b54ad81f8b52), but haven't submitted to https://github.com/DefinitelyTyped/DefinitelyTyped yet. Something is off about the way I authored them such that `arethetypeswrong` shows there's [an issue](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/FalseCJS.md) with them ([help requested](https://discord.com/channels/508357248330760243/757992230077333655/1321871588580397170)).

So far we have these embedded in our repo, so that's good enough for now, for us at least.

**Comment by mattdesl** [comment]
Hey all, I've added `types.d.ts` to the repo in the latest version (`1.1.8`) which should hopefully cover most of the API. Please test and let me know if this solves the issue or if there's a better way to achieve it.

I don't know yet why `import { sRGB, convert } from '@texel/color'` doesn't seem to pick up the color spaces (sRGB, A98RGBLinear, etc) but the `convert` function is picked up properly.

**Comment by bengry** [comment]
> Hey all, I've added `types.d.ts` to the repo in the latest version (`1.1.8`) which should hopefully cover most of the API. Please test and let me know if this solves the issue or if there's a better way to achieve it.
> 
> For vscode's autocomplete, I don't know yet why `import { sRGB, convert } from '@texel/color'` doesn't seem to pick up the color spaces (sRGB, A98RGBLinear, etc) but the `convert` function is picked up properly.

Thanks @mattdesl. https://github.com/texel-org/color/pull/10 should fix the issue you mentioned.

**Comment by mattdesl** [comment]
Thanks, this should be fixed now. Seems to be much easier to use in VSCode thanks to the types!

**Comment by skorphil** [comment]
Thats great. I had to use ignore ts directives earlier.

Love the performance of the library
